import api from "./api"
import { useState } from "react"

const liga = [
                "FA Women's Super League|England", "Premier League|England", "Champions League|Europe", "UEFA Women's Euro|Europe", "UEFA Euro|Europe", 
                "Bundesliga|Germany", "La Liga|Spain", "Liga h", "Liga i", 
                "Ligue 1|France", "Liga k", "Liga l", "Liga m", "Liga n", "Liga o", "Liga p", "Liga q", "Liga r"
            ]

const clubs = [
    {"id": 212, "name": "Atlético Madrid"},
    {"id": 220, "name": "Real Madrid"},
    {"id": 217, "name": "Barcelona"},
    {"id": 210, "name": "Real Sociedad"},
    {"id": 422, "name": "Osasuna"},
    {"id": 901, "name": "Real Valladolid"},
    {"id": 360, "name": "Rayo Vallecano"},
    {"id": 223, "name": "Málaga"},
    {"id": 207, "name": "Valencia"},
    {"id": 221, "name": "Levante UD"},
    {"id": 213, "name": "Sevilla"},
    {"id": 209, "name": "Celta Vigo"},
    {"id": 214, "name": "Espanyol"},
    {"id": 1042, "name": "Elche"},
    {"id": 403, "name": "Almería"},
    {"id": 215, "name": "Athletic Club"},
    {"id": 222, "name": "Villarreal"},
    {"id": 216, "name": "Getafe"},
    {"id": 218, "name": "Real Betis"},
    {"id": 1049, "name": "Granada"},
    {"id": 39, "name": "Manchester United"},
    {"id": 219, "name": "RC Deportivo La Coruña"},
    {"id": 1041, "name": "Sporting Gijón"},
    {"id": 1043, "name": "Mallorca"},
    {"id": 1218, "name": "Hércules"},
    {"id": 395, "name": "Real Zaragoza"},
    {"id": 1217, "name": "Racing Santander"},
    {"id": 24, "name": "Liverpool"},
    {"id": 243, "name": "AC Milan"},
    {"id": 608, "name": "Albacete"},
    {"id": 1220, "name": "Recreativo Huelva"},
    {"id": 1230, "name": "Real Murcia CF"},
    {"id": 7282, "name": "ATK Mohun Bagan"},
    {"id": 7285, "name": "NorthEast United"},
    {"id": 7286, "name": "East Bengal"},
    {"id": 2021, "name": "Jamshedpur"},
    {"id": 7287, "name": "Mumbai City"},
    {"id": 7291, "name": "Odisha"},
    {"id": 7289, "name": "Hyderabad"},
    {"id": 7284, "name": "Bengaluru"},
    {"id": 7290, "name": "Chennaiyin"},
    {"id": 7283, "name": "Kerala Blasters"},
    {"id": 7288, "name": "Goa"},
    {"id": 238, "name": "Inter Milan"},
    {"id": 169, "name": "Bayern Munich"},
    {"id": 627, "name": "Tenerife"},
    {"id": 1219, "name": "Xerez"},
    {"id": 224, "name": "Juventus"},
    {"id": 322, "name": "Eibar"},
    {"id": 373, "name": "Córdoba CF"},
    {"id": 2391, "name": "Morocco Women's"},
    {"id": 1211, "name": "Korea Republic Women's"},
    {"id": 16769, "name": "Vietnam Women's"},
    {"id": 1214, "name": "United States Women's"},
    {"id": 1207, "name": "China PR Women's"},
    {"id": 853, "name": "Denmark Women's"},
    {"id": 1213, "name": "Nigeria Women's"},
    {"id": 865, "name": "England Women's"},
    {"id": 1832, "name": "Costa Rica Women's"},
    {"id": 1210, "name": "Japan Women's"},
    {"id": 852, "name": "Norway Women's"},
    {"id": 1215, "name": "New Zealand Women's"},
    {"id": 858, "name": "Sweden Women's"},
    {"id": 863, "name": "Spain Women's"},
    {"id": 864, "name": "Portugal Women's"},
    {"id": 851, "name": "Netherlands Women's"},
    {"id": 2355, "name": "Haiti Women's"},
    {"id": 857, "name": "Germany Women's"},
    {"id": 1216, "name": "South Africa Women's"},
    {"id": 6045, "name": "Zambia Women's"},
    {"id": 861, "name": "France Women's"},
    {"id": 1205, "name": "Australia Women's"},
    {"id": 16803, "name": "Panama Women's"},
    {"id": 16802, "name": "Colombia Women's"},
    {"id": 1212, "name": "Jamaica Women's"},
    {"id": 16768, "name": "Republic of Ireland Women's"},
    {"id": 1206, "name": "Canada Women's"},
    {"id": 1204, "name": "Argentina Women's"},
    {"id": 860, "name": "Switzerland Women's"},
    {"id": 1106, "name": "Philippines Women's"},
    {"id": 1203, "name": "Brazil Women's"},
    {"id": 855, "name": "Italy Women's"},
    {"id": 2647, "name": "Aston Villa"},
    {"id": 972, "name": "West Ham United LFC"},
    {"id": 965, "name": "Brighton & Hove Albion WFC"},
    {"id": 749, "name": "Tottenham Hotspur Women"},
    {"id": 969, "name": "Birmingham City WFC"},
    {"id": 973, "name": "Bristol City WFC"},
    {"id": 746, "name": "Manchester City WFC"},
    {"id": 974, "name": "Reading WFC"},
    {"id": 968, "name": "Arsenal WFC"},
    {"id": 1475, "name": "Manchester United"},
    {"id": 971, "name": "Chelsea FCW"},
    {"id": 967, "name": "Everton LFC"},
    {"id": 902, "name": "Huesca"},
    {"id": 552, "name": "Cádiz"},
    {"id": 206, "name": "Deportivo Alavés"},
    {"id": 205, "name": "Leganés"},
    {"id": 211, "name": "Girona"},
    {"id": 208, "name": "Las Palmas"},
    {"id": 759, "name": "Washington Spirit"},
    {"id": 767, "name": "Utah Royals"},
    {"id": 766, "name": "North Carolina Courage"},
    {"id": 761, "name": "Chicago Red Stars"},
    {"id": 765, "name": "Portland Thorns"},
    {"id": 764, "name": "Orlando Pride"},
    {"id": 762, "name": "Houston Dash"},
    {"id": 760, "name": "OL Reign"},
    {"id": 793, "name": "Iceland"},
    {"id": 775, "name": "Nigeria"},
    {"id": 779, "name": "Argentina"},
    {"id": 771, "name": "France"},
    {"id": 768, "name": "England"},
    {"id": 790, "name": "Sweden"},
    {"id": 773, "name": "Switzerland"},
    {"id": 781, "name": "Brazil"},
    {"id": 782, "name": "Belgium"},
    {"id": 791, "name": "South Korea"},
    {"id": 796, "name": "Russia"},
    {"id": 772, "name": "Spain"},
    {"id": 794, "name": "Mexico"},
    {"id": 797, "name": "Iran"},
    {"id": 778, "name": "Japan"},
    {"id": 769, "name": "Colombia"},
    {"id": 786, "name": "Serbia"},
    {"id": 785, "name": "Croatia"},
    {"id": 770, "name": "Germany"},
    {"id": 777, "name": "Tunisia"},
    {"id": 795, "name": "Costa Rica"},
    {"id": 776, "name": "Denmark"},
    {"id": 788, "name": "Morocco"},
    {"id": 783, "name": "Uruguay"},
    {"id": 774, "name": "Egypt"},
    {"id": 789, "name": "Poland"},
    {"id": 799, "name": "Saudi Arabia"},
    {"id": 787, "name": "Senegal"},
    {"id": 780, "name": "Portugal"},
    {"id": 798, "name": "Panama"},
    {"id": 784, "name": "Peru"},
    {"id": 792, "name": "Australia"},
    {"id": 970, "name": "Yeovil Town LFC"},
    {"id": 966, "name": "Liverpool WFC"},
    {"id": 38, "name": "Tottenham Hotspur"},
    {"id": 920, "name": "WNT Finland"},
    {"id": 862, "name": "Iceland Women's"},
    {"id": 854, "name": "Belgium Women's"},
    {"id": 2457, "name": "Northern Ireland"},
    {"id": 859, "name": "Austria Women's"},
    {"id": 1833, "name": "Canada"},
    {"id": 941, "name": "Netherlands"},
    {"id": 2722, "name": "Cameroon"},
    {"id": 1839, "name": "United States"},
    {"id": 907, "name": "Wales"},
    {"id": 4885, "name": "Ghana"},
    {"id": 3566, "name": "Qatar"},
    {"id": 3565, "name": "Ecuador"},
    {"id": 1, "name": "Arsenal"},
    {"id": 33, "name": "Chelsea"},
    {"id": 75, "name": "Charlton Athletic"},
    {"id": 46, "name": "Wolverhampton Wanderers"},
    {"id": 98, "name": "Blackburn Rovers"},
    {"id": 328, "name": "Bolton Wanderers"},
    {"id": 25, "name": "Southampton"},
    {"id": 55, "name": "Fulham"},
    {"id": 37, "name": "Newcastle United"},
    {"id": 59, "name": "Aston Villa"},
    {"id": 54, "name": "Birmingham City"},
    {"id": 101, "name": "Leeds United"},
    {"id": 105, "name": "Portsmouth"},
    {"id": 22, "name": "Leicester City"},
    {"id": 47, "name": "Middlesbrough"},
    {"id": 29, "name": "Everton"},
    {"id": 36, "name": "Manchester City"},
    {"id": 256, "name": "FC Porto"},
    {"id": 129, "name": "AS Monaco"},
    {"id": 2358, "name": "North Macedonia"},
    {"id": 914, "name": "Italy"},
    {"id": 908, "name": "Slovakia"},
    {"id": 915, "name": "Austria"},
    {"id": 942, "name": "Scotland"},
    {"id": 911, "name": "Ukraine"},
    {"id": 916, "name": "Hungary"},
    {"id": 912, "name": "Czech Republic"},
    {"id": 909, "name": "Turkey"},
    {"id": 1835, "name": "Finland"},
    {"id": 1208, "name": "Cameroon Women's"},
    {"id": 1209, "name": "Chile Women's"},
    {"id": 866, "name": "Scotland Women's"},
    {"id": 1107, "name": "Thailand Women's"},
    {"id": 228, "name": "Atalanta"},
    {"id": 240, "name": "Bologna"},
    {"id": 229, "name": "AS Roma"},
    {"id": 241, "name": "Torino"},
    {"id": 233, "name": "Genoa"},
    {"id": 231, "name": "Chievo"},
    {"id": 226, "name": "Hellas Verona"},
    {"id": 232, "name": "Sassuolo"},
    {"id": 234, "name": "Sampdoria"},
    {"id": 1683, "name": "Carpi"},
    {"id": 239, "name": "Fiorentina"},
    {"id": 290, "name": "Empoli"},
    {"id": 230, "name": "Udinese"},
    {"id": 236, "name": "Lazio"},
    {"id": 227, "name": "Napoli"},
    {"id": 2256, "name": "Palermo"},
    {"id": 291, "name": "Frosinone"},
    {"id": 137, "name": "Lyon"},
    {"id": 136, "name": "OGC Nice"},
    {"id": 134, "name": "Rennes"},
    {"id": 160, "name": "Gazélec Ajaccio"},
    {"id": 143, "name": "Lille"},
    {"id": 139, "name": "Montpellier"},
    {"id": 2736, "name": "Bastia"},
    {"id": 131, "name": "Paris Saint-Germain"},
    {"id": 146, "name": "Bordeaux"},
    {"id": 144, "name": "Nantes"},
    {"id": 133, "name": "Troyes"},
    {"id": 147, "name": "Marseille"},
    {"id": 140, "name": "Caen"},
    {"id": 145, "name": "Angers"},
    {"id": 156, "name": "Stade de Reims"},
    {"id": 142, "name": "Guingamp"},
    {"id": 130, "name": "Toulouse"},
    {"id": 165, "name": "Lorient"},
    {"id": 135, "name": "Saint-Étienne"},
    {"id": 26, "name": "Swansea City"},
    {"id": 23, "name": "Watford"},
    {"id": 56, "name": "Norwich City"},
    {"id": 31, "name": "Crystal Palace"},
    {"id": 30, "name": "Stoke City"},
    {"id": 27, "name": "West Bromwich Albion"},
    {"id": 41, "name": "Sunderland"},
    {"id": 40, "name": "West Ham United"},
    {"id": 28, "name": "AFC Bournemouth"},
    {"id": 177, "name": "FSV Mainz 05"},
    {"id": 184, "name": "Eintracht Frankfurt"},
    {"id": 180, "name": "Borussia Dortmund"},
    {"id": 172, "name": "Augsburg"},
    {"id": 189, "name": "Ingolstadt"},
    {"id": 872, "name": "Darmstadt 98"},
    {"id": 178, "name": "Hannover 96"},
    {"id": 173, "name": "Hertha Berlin"}
]

const league = [
    {"value": 1, "Label": "FA Women's Super League"},
    {"value": 2, "Label": "Premier League"},
    {"value": 3, "Label": "Champions League"},
    {"value": 4, "Label": "UEFA Women's Euro"},
    {"value": 5, "Label": "UEFA Euro", "region": "Europe"},
    {"value": 6, "Label": "Ligue 1"},
    {"value": 7, "Label": "Bundesliga"},
    {"value": 8, "Label": "La Liga"},
    {"value": 9, "Label": "NWSL"},
    {"value": 10, "Label": "Serie A"},
    {"value": 11, "Label": "Indian Super League"},
    {"value": 12, "Label": "FIFA World Cup"},
    {"value": 13, "Label": "Women's World Cup"}
  ]
const pais = ["França", "Brasil", "Italia", "Espanha"]

const posicao = ["Zagueiro", "Volante","Atacante"]

const idades = [16,18,21,24,27,30,32,35]


var isLogged = false

const players = [

    {"Rank": 1, "Jogador": "T. Alexander-Arnold", "Time": "Sampaio Corrêa", "País": "República Centro-Africada", "Posição": "VOL", "Idade": 45, "Assist./90min":0.053,"Gols/90 min.":0.053,"Ações/90min":80,"Val. Médio/ Ação":0.006,"Rating":0.480,"Valor":"180 M €"},
    {"Rank": 2, "Jogador": "S. Aguero", "Time": "Flamengo", "País": "Nigéria", "Posição": "ATA", "Idade": 32, "Assist./90min": 0.045, "Gols/90 min.": 0.072, "Ações/90min": 75, "Val. Médio/ Ação": 0.008, "Rating": 0.520, "Valor": "200 M €"},
    {"Rank": 3, "Jogador": "L. Modric", "Time": "Atlético Mineiro", "País": "Croácia", "Posição": "MEI", "Idade": 35, "Assist./90min": 0.068, "Gols/90 min.": 0.035, "Ações/90min": 88, "Val. Médio/ Ação": 0.007, "Rating": 0.485, "Valor": "150 M €"},    
    {"Rank": 4, "Jogador": "K. De Bruyne", "Time": "Palmeiras", "País": "Bélgica", "Posição": "MEI", "Idade": 29, "Assist./90min": 0.080, "Gols/90 min.": 0.065, "Ações/90min": 92, "Val. Médio/ Ação": 0.009, "Rating": 0.550, "Valor": "220 M €"},    
    {"Rank": 5, "Jogador": "N. Kanté", "Time": "Corinthians", "País": "França", "Posição": "VOL", "Idade": 30, "Assist./90min": 0.060, "Gols/90 min.": 0.040, "Ações/90min": 85, "Val. Médio/ Ação": 0.006, "Rating": 0.510, "Valor": "180 M €"},    
    {"Rank": 6, "Jogador": "R. Sterling", "Time": "Cruzeiro", "País": "Inglaterra", "Posição": "ATA", "Idade": 26, "Assist./90min": 0.055, "Gols/90 min.": 0.075, "Ações/90min": 78, "Val. Médio/ Ação": 0.008, "Rating": 0.525, "Valor": "190 M €"},    
    {"Rank": 7, "Jogador": "V. van Dijk", "Time": "Vasco da Gama", "País": "Holanda", "Posição": "ZAG", "Idade": 29, "Assist./90min": 0.030, "Gols/90 min.": 0.025, "Ações/90min": 89, "Val. Médio/ Ação": 0.010, "Rating": 0.540, "Valor": "210 M €"},    
    {"Rank": 8, "Jogador": "M. Salah", "Time": "Internacional", "País": "Egito", "Posição": "ATA", "Idade": 28, "Assist./90min": 0.070, "Gols/90 min.": 0.080, "Ações/90min": 82, "Val. Médio/ Ação": 0.007, "Rating": 0.560, "Valor": "230 M €"},    
    {"Rank": 9, "Jogador": "B. Fernandes", "Time": "Santos", "País": "Portugal", "Posição": "MEI", "Idade": 27, "Assist./90min": 0.075, "Gols/90 min.": 0.060, "Ações/90min": 90, "Val. Médio/ Ação": 0.008, "Rating": 0.545, "Valor": "200 M €"},    
    {"Rank": 10, "Jogador": "A. Robertson", "Time": "Grêmio", "País": "Escócia", "Posição": "LAD", "Idade": 27, "Assist./90min": 0.048, "Gols/90 min.": 0.030, "Ações/90min": 87, "Val. Médio/ Ação": 0.009, "Rating": 0.500, "Valor": "170 M €"},    
    {"Rank": 11, "Jogador": "J. Kimmich", "Time": "Botafogo", "País": "Alemanha", "Posição": "MEI", "Idade": 26, "Assist./90min": 0.065, "Gols/90 min.": 0.050, "Ações/90min": 86, "Val. Médio/ Ação": 0.007, "Rating": 0.535, "Valor": "190 M €"},    
    {"Rank": 12, "Jogador": "H. Kane", "Time": "Bahia", "País": "Inglaterra", "Posição": "ATA", "Idade": 28, "Assist./90min": 0.055, "Gols/90 min.": 0.090, "Ações/90min": 80, "Val. Médio/ Ação": 0.010, "Rating": 0.570, "Valor": "240 M €"},    
    {"Rank": 13, "Jogador": "C. Pulisic", "Time": "Fortaleza", "País": "Estados Unidos", "Posição": "ATA", "Idade": 23, "Assist./90min": 0.072, "Gols/90 min.": 0.055, "Ações/90min": 79, "Val. Médio/ Ação": 0.008, "Rating": 0.525, "Valor": "180 M €"},
    {"Rank": 14, "Jogador": "E. Haaland", "Time": "Atlético Paranaense", "País": "Noruega", "Posição": "ATA", "Idade": 21, "Assist./90min": 0.040, "Gols/90 min.": 0.100, "Ações/90min": 75, "Val. Médio/ Ação": 0.012, "Rating": 0.590, "Valor": "260 M €"},    
    {"Rank": 15, "Jogador": "A. Laporte", "Time": "Chapecoense", "País": "Espanha", "Posição": "ZAG", "Idade": 27, "Assist./90min": 0.035, "Gols/90 min.": 0.020, "Ações/90min": 88, "Val. Médio/ Ação": 0.009, "Rating": 0.515, "Valor": "160 M €"}
]
export default {
    liga,
    pais,
    posicao,
    idades,
    players,
    isLogged,
    league,
}