import api from "./api"
import { useState } from "react"

const clubs = [
    {"id": 212, "name": "Atlético Madrid"},
    {"id": 220, "name": "Real Madrid"},
    {"id": 217, "name": "Barcelona"},
    {"id": 210, "name": "Real Sociedad"},
    {"id": 422, "name": "Osasuna"},
    {"id": 901, "name": "Real Valladolid"},
    {"id": 360, "name": "Rayo Vallecano"},
    {"id": 223, "name": "Málaga"},
    {"id": 207, "name": "Valencia"},
    {"id": 221, "name": "Levante UD"},
    {"id": 213, "name": "Sevilla"},
    {"id": 209, "name": "Celta Vigo"},
    {"id": 214, "name": "Espanyol"},
    {"id": 1042, "name": "Elche"},
    {"id": 403, "name": "Almería"},
    {"id": 215, "name": "Athletic Club"},
    {"id": 222, "name": "Villarreal"},
    {"id": 216, "name": "Getafe"},
    {"id": 218, "name": "Real Betis"},
    {"id": 1049, "name": "Granada"},
    {"id": 39, "name": "Manchester United"},
    {"id": 219, "name": "RC Deportivo La Coruña"},
    {"id": 1041, "name": "Sporting Gijón"},
    {"id": 1043, "name": "Mallorca"},
    {"id": 1218, "name": "Hércules"},
    {"id": 395, "name": "Real Zaragoza"},
    {"id": 1217, "name": "Racing Santander"},
    {"id": 24, "name": "Liverpool"},
    {"id": 243, "name": "AC Milan"},
    {"id": 608, "name": "Albacete"},
    {"id": 1220, "name": "Recreativo Huelva"},
    {"id": 1230, "name": "Real Murcia CF"},
    {"id": 7282, "name": "ATK Mohun Bagan"},
    {"id": 7285, "name": "NorthEast United"},
    {"id": 7286, "name": "East Bengal"},
    {"id": 2021, "name": "Jamshedpur"},
    {"id": 7287, "name": "Mumbai City"},
    {"id": 7291, "name": "Odisha"},
    {"id": 7289, "name": "Hyderabad"},
    {"id": 7284, "name": "Bengaluru"},
    {"id": 7290, "name": "Chennaiyin"},
    {"id": 7283, "name": "Kerala Blasters"},
    {"id": 7288, "name": "Goa"},
    {"id": 238, "name": "Inter Milan"},
    {"id": 169, "name": "Bayern Munich"},
    {"id": 627, "name": "Tenerife"},
    {"id": 1219, "name": "Xerez"},
    {"id": 224, "name": "Juventus"},
    {"id": 322, "name": "Eibar"},
    {"id": 373, "name": "Córdoba CF"},
    {"id": 2391, "name": "Morocco Women's"},
    {"id": 1211, "name": "Korea Republic Women's"},
    {"id": 16769, "name": "Vietnam Women's"},
    {"id": 1214, "name": "United States Women's"},
    {"id": 1207, "name": "China PR Women's"},
    {"id": 853, "name": "Denmark Women's"},
    {"id": 1213, "name": "Nigeria Women's"},
    {"id": 865, "name": "England Women's"},
    {"id": 1832, "name": "Costa Rica Women's"},
    {"id": 1210, "name": "Japan Women's"},
    {"id": 852, "name": "Norway Women's"},
    {"id": 1215, "name": "New Zealand Women's"},
    {"id": 858, "name": "Sweden Women's"},
    {"id": 863, "name": "Spain Women's"},
    {"id": 864, "name": "Portugal Women's"},
    {"id": 851, "name": "Netherlands Women's"},
    {"id": 2355, "name": "Haiti Women's"},
    {"id": 857, "name": "Germany Women's"},
    {"id": 1216, "name": "South Africa Women's"},
    {"id": 6045, "name": "Zambia Women's"},
    {"id": 861, "name": "France Women's"},
    {"id": 1205, "name": "Australia Women's"},
    {"id": 16803, "name": "Panama Women's"},
    {"id": 16802, "name": "Colombia Women's"},
    {"id": 1212, "name": "Jamaica Women's"},
    {"id": 16768, "name": "Republic of Ireland Women's"},
    {"id": 1206, "name": "Canada Women's"},
    {"id": 1204, "name": "Argentina Women's"},
    {"id": 860, "name": "Switzerland Women's"},
    {"id": 1106, "name": "Philippines Women's"},
    {"id": 1203, "name": "Brazil Women's"},
    {"id": 855, "name": "Italy Women's"},
    {"id": 2647, "name": "Aston Villa"},
    {"id": 972, "name": "West Ham United LFC"},
    {"id": 965, "name": "Brighton & Hove Albion WFC"},
    {"id": 749, "name": "Tottenham Hotspur Women"},
    {"id": 969, "name": "Birmingham City WFC"},
    {"id": 973, "name": "Bristol City WFC"},
    {"id": 746, "name": "Manchester City WFC"},
    {"id": 974, "name": "Reading WFC"},
    {"id": 968, "name": "Arsenal WFC"},
    {"id": 1475, "name": "Manchester United"},
    {"id": 971, "name": "Chelsea FCW"},
    {"id": 967, "name": "Everton LFC"},
    {"id": 902, "name": "Huesca"},
    {"id": 552, "name": "Cádiz"},
    {"id": 206, "name": "Deportivo Alavés"},
    {"id": 205, "name": "Leganés"},
    {"id": 211, "name": "Girona"},
    {"id": 208, "name": "Las Palmas"},
    {"id": 759, "name": "Washington Spirit"},
    {"id": 767, "name": "Utah Royals"},
    {"id": 766, "name": "North Carolina Courage"},
    {"id": 761, "name": "Chicago Red Stars"},
    {"id": 765, "name": "Portland Thorns"},
    {"id": 764, "name": "Orlando Pride"},
    {"id": 762, "name": "Houston Dash"},
    {"id": 760, "name": "OL Reign"},
    {"id": 793, "name": "Iceland"},
    {"id": 775, "name": "Nigeria"},
    {"id": 779, "name": "Argentina"},
    {"id": 771, "name": "France"},
    {"id": 768, "name": "England"},
    {"id": 790, "name": "Sweden"},
    {"id": 773, "name": "Switzerland"},
    {"id": 781, "name": "Brazil"},
    {"id": 782, "name": "Belgium"},
    {"id": 791, "name": "South Korea"},
    {"id": 796, "name": "Russia"},
    {"id": 772, "name": "Spain"},
    {"id": 794, "name": "Mexico"},
    {"id": 797, "name": "Iran"},
    {"id": 778, "name": "Japan"},
    {"id": 769, "name": "Colombia"},
    {"id": 786, "name": "Serbia"},
    {"id": 785, "name": "Croatia"},
    {"id": 770, "name": "Germany"},
    {"id": 777, "name": "Tunisia"},
    {"id": 795, "name": "Costa Rica"},
    {"id": 776, "name": "Denmark"},
    {"id": 788, "name": "Morocco"},
    {"id": 783, "name": "Uruguay"},
    {"id": 774, "name": "Egypt"},
    {"id": 789, "name": "Poland"},
    {"id": 799, "name": "Saudi Arabia"},
    {"id": 787, "name": "Senegal"},
    {"id": 780, "name": "Portugal"},
    {"id": 798, "name": "Panama"},
    {"id": 784, "name": "Peru"},
    {"id": 792, "name": "Australia"},
    {"id": 970, "name": "Yeovil Town LFC"},
    {"id": 966, "name": "Liverpool WFC"},
    {"id": 38, "name": "Tottenham Hotspur"},
    {"id": 920, "name": "WNT Finland"},
    {"id": 862, "name": "Iceland Women's"},
    {"id": 854, "name": "Belgium Women's"},
    {"id": 2457, "name": "Northern Ireland"},
    {"id": 859, "name": "Austria Women's"},
    {"id": 1833, "name": "Canada"},
    {"id": 941, "name": "Netherlands"},
    {"id": 2722, "name": "Cameroon"},
    {"id": 1839, "name": "United States"},
    {"id": 907, "name": "Wales"},
    {"id": 4885, "name": "Ghana"},
    {"id": 3566, "name": "Qatar"},
    {"id": 3565, "name": "Ecuador"},
    {"id": 1, "name": "Arsenal"},
    {"id": 33, "name": "Chelsea"},
    {"id": 75, "name": "Charlton Athletic"},
    {"id": 46, "name": "Wolverhampton Wanderers"},
    {"id": 98, "name": "Blackburn Rovers"},
    {"id": 328, "name": "Bolton Wanderers"},
    {"id": 25, "name": "Southampton"},
    {"id": 55, "name": "Fulham"},
    {"id": 37, "name": "Newcastle United"},
    {"id": 59, "name": "Aston Villa"},
    {"id": 54, "name": "Birmingham City"},
    {"id": 101, "name": "Leeds United"},
    {"id": 105, "name": "Portsmouth"},
    {"id": 22, "name": "Leicester City"},
    {"id": 47, "name": "Middlesbrough"},
    {"id": 29, "name": "Everton"},
    {"id": 36, "name": "Manchester City"},
    {"id": 256, "name": "FC Porto"},
    {"id": 129, "name": "AS Monaco"},
    {"id": 2358, "name": "North Macedonia"},
    {"id": 914, "name": "Italy"},
    {"id": 908, "name": "Slovakia"},
    {"id": 915, "name": "Austria"},
    {"id": 942, "name": "Scotland"},
    {"id": 911, "name": "Ukraine"},
    {"id": 916, "name": "Hungary"},
    {"id": 912, "name": "Czech Republic"},
    {"id": 909, "name": "Turkey"},
    {"id": 1835, "name": "Finland"},
    {"id": 1208, "name": "Cameroon Women's"},
    {"id": 1209, "name": "Chile Women's"},
    {"id": 866, "name": "Scotland Women's"},
    {"id": 1107, "name": "Thailand Women's"},
    {"id": 228, "name": "Atalanta"},
    {"id": 240, "name": "Bologna"},
    {"id": 229, "name": "AS Roma"},
    {"id": 241, "name": "Torino"},
    {"id": 233, "name": "Genoa"},
    {"id": 231, "name": "Chievo"},
    {"id": 226, "name": "Hellas Verona"},
    {"id": 232, "name": "Sassuolo"},
    {"id": 234, "name": "Sampdoria"},
    {"id": 1683, "name": "Carpi"},
    {"id": 239, "name": "Fiorentina"},
    {"id": 290, "name": "Empoli"},
    {"id": 230, "name": "Udinese"},
    {"id": 236, "name": "Lazio"},
    {"id": 227, "name": "Napoli"},
    {"id": 2256, "name": "Palermo"},
    {"id": 291, "name": "Frosinone"},
    {"id": 137, "name": "Lyon"},
    {"id": 136, "name": "OGC Nice"},
    {"id": 134, "name": "Rennes"},
    {"id": 160, "name": "Gazélec Ajaccio"},
    {"id": 143, "name": "Lille"},
    {"id": 139, "name": "Montpellier"},
    {"id": 2736, "name": "Bastia"},
    {"id": 131, "name": "Paris Saint-Germain"},
    {"id": 146, "name": "Bordeaux"},
    {"id": 144, "name": "Nantes"},
    {"id": 133, "name": "Troyes"},
    {"id": 147, "name": "Marseille"},
    {"id": 140, "name": "Caen"},
    {"id": 145, "name": "Angers"},
    {"id": 156, "name": "Stade de Reims"},
    {"id": 142, "name": "Guingamp"},
    {"id": 130, "name": "Toulouse"},
    {"id": 165, "name": "Lorient"},
    {"id": 135, "name": "Saint-Étienne"},
    {"id": 26, "name": "Swansea City"},
    {"id": 23, "name": "Watford"},
    {"id": 56, "name": "Norwich City"},
    {"id": 31, "name": "Crystal Palace"},
    {"id": 30, "name": "Stoke City"},
    {"id": 27, "name": "West Bromwich Albion"},
    {"id": 41, "name": "Sunderland"},
    {"id": 40, "name": "West Ham United"},
    {"id": 28, "name": "AFC Bournemouth"},
    {"id": 177, "name": "FSV Mainz 05"},
    {"id": 184, "name": "Eintracht Frankfurt"},
    {"id": 180, "name": "Borussia Dortmund"},
    {"id": 172, "name": "Augsburg"},
    {"id": 189, "name": "Ingolstadt"},
    {"id": 872, "name": "Darmstadt 98"},
    {"id": 178, "name": "Hannover 96"},
    {"id": 173, "name": "Hertha Berlin"}
]

const league = [
    {"value": 1, "Label": "FA Women's Super League"},
    {"value": 2, "Label": "Premier League"},
    {"value": 3, "Label": "Champions League"},
    {"value": 4, "Label": "UEFA Women's Euro"},
    {"value": 5, "Label": "UEFA Euro", "region": "Europe"},
    {"value": 6, "Label": "Ligue 1"},
    {"value": 7, "Label": "Bundesliga"},
    {"value": 8, "Label": "La Liga"},
    {"value": 9, "Label": "NWSL"},
    {"value": 10, "Label": "Serie A"},
    {"value": 11, "Label": "Indian Super League"},
    {"value": 12, "Label": "FIFA World Cup"},
    {"value": 13, "Label": "Women's World Cup"}
  ]
const pais = ["França", "Brasil", "Italia", "Espanha"]

const posicao = ["Zagueiro", "Volante","Atacante"]

const idades = [16,18,21,24,27,30,32,35]

const names = ["Jorge Verdade","Mauricio da Serra","José da Silve","João Pé de Feijão"]

var isLogged = false

const players = [
    
    {"Rank": 1, "Jogador": "Lionel Messi", "Posição": "ATA", "Time": "Paris Saint-Germain", "País": "Argentina", "Valor": "150 M €", "Idade": 35, "Assist": 0.120, "Gols": 1.10, "Acoes": 110, "ValorAcao": 0.015, "Rating": 0.980},
    {"Rank": 2, "Jogador": "Robert Lewandowski", "Posição": "ATA", "Time": "Bayern Munich", "País": "Polônia", "Valor": "90 M €", "Idade": 33, "Assist": 0.045, "Gols": 1.20, "Acoes": 105, "ValorAcao": 0.009, "Rating": 0.970},
    {"Rank": 3, "Jogador": "Cristiano Ronaldo", "Posição": "ATA", "Time": "Manchester United", "País": "Portugal", "Valor": "80 M €", "Idade": 36, "Assist": 0.085, "Gols": 0.90, "Acoes": 100, "ValorAcao": 0.008, "Rating": 0.950},
    {"Rank": 4, "Jogador": "Mohamed Salah", "Posição": "ATA", "Time": "Liverpool", "País": "Egito", "Valor": "110 M €", "Idade": 29, "Assist": 0.110, "Gols": 0.95, "Acoes": 98, "ValorAcao": 0.013, "Rating": 0.940},
    {"Rank": 5, "Jogador": "Erling Haaland", "Posição": "ATA", "Time": "Borussia Dortmund", "País": "Noruega", "Valor": "120 M €", "Idade": 21, "Assist": 0.055, "Gols": 1.30, "Acoes": 100, "ValorAcao": 0.012, "Rating": 0.940},
    {"Rank": 6, "Jogador": "Kevin De Bruyne", "Posição": "MEI", "Time": "Manchester City", "País": "Bélgica", "Valor": "100 M €", "Idade": 30, "Assist": 0.150, "Gols": 0.065, "Acoes": 95, "ValorAcao": 0.011, "Rating": 0.920},
    {"Rank": 7, "Jogador": "Neymar", "Posição": "ATA", "Time": "Paris Saint-Germain", "País": "Brasil", "Valor": "120 M €", "Idade": 30, "Assist": 0.098, "Gols": 0.75, "Acoes": 95, "ValorAcao": 0.012, "Rating": 0.920},
    {"Rank": 8, "Jogador": "Sadio Mané", "Posição": "ATA", "Time": "Liverpool", "País": "Senegal", "Valor": "100 M €", "Idade": 30, "Assist": 0.090, "Gols": 0.85, "Acoes": 98, "ValorAcao": 0.011, "Rating": 0.920},
    {"Rank": 9, "Jogador": "Gianluigi Donnarumma", "Posição": "GOL", "Time": "Paris Saint-Germain", "País": "Itália", "Valor": "60 M €", "Idade": 22, "Assist": 0.000, "Gols": 0.000, "Acoes": 50, "ValorAcao": 0.012, "Rating": 0.920},
    {"Rank": 10, "Jogador": "Bruno Fernandes", "Posição": "MEI", "Time": "Manchester United", "País": "Portugal", "Valor": "90 M €", "Idade": 27, "Assist": 0.160, "Gols": 0.085, "Acoes": 92, "ValorAcao": 0.010, "Rating": 0.910},
    {"Rank": 11, "Jogador": "João Cancelo", "Posição": "LAD", "Time": "Manchester City", "País": "Portugal", "Valor": "70 M €", "Idade": 28, "Assist": 0.110, "Gols": 0.035, "Acoes": 88, "ValorAcao": 0.009, "Rating": 0.910},
    {"Rank": 12, "Jogador": "Raheem Sterling", "Posição": "ATA", "Time": "Manchester City", "País": "Inglaterra", "Valor": "80 M €", "Idade": 27, "Assist": 0.120, "Gols": 0.75, "Acoes": 95, "ValorAcao": 0.008, "Rating": 0.900},
    {"Rank": 13, "Jogador": "Sergio Ramos", "Posição": "ZAG", "Time": "Paris Saint-Germain", "País": "Espanha", "Valor": "20 M €", "Idade": 35, "Assist": 0.030, "Gols": 0.035, "Acoes": 75, "ValorAcao": 0.005, "Rating": 0.850},
    {"Rank": 14, "Jogador": "Kylian Mbappé", "Posição": "ATA", "Time": "Paris Saint-Germain", "País": "França", "Valor": "180 M €", "Idade": 23, "Assist": 0.140, "Gols": 1.15, "Acoes": 105, "ValorAcao": 0.017, "Rating": 0.960},
    {"Rank": 15, "Jogador": "Fabinho", "Posição": "VOL", "Time": "Al-Ittihad", "País": "Brasil", "Valor": "42 M €", "Idade": 29, "Assist": 0.053, "Gols": 0.053, "Acoes": 80, "ValorAcao": 0.006, "Rating": 0.480},
  ]
  
export default {
    pais,
    posicao,
    idades,
    players,
    isLogged,
    league,
    names,
    clubs
}